# Generated by Django 3.2.10 on 2022-03-31 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0002_auto_20220330_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='bpm',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
    ]
