# Generated by Django 3.2.10 on 2022-03-31 02:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0004_auto_20220330_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
    ]
